use_frameworks!

target 'Bitso_Example' do
  pod 'Bitso', :path => '../'

  target 'Bitso_Tests' do
    inherit! :search_paths
    pod 'Specta'
    pod 'Bitso', :path => '../'
    pod 'OHHTTPStubs'
    
  pod 'Expecta'
  pod 'Mantle'
  pod 'AFNetworking'
  end
end
